-- THV Donor Dashboard production schema for Supabase PostgreSQL.
-- This migration intentionally preserves the current field names and text IDs so
-- existing dashboard code and the one-time MySQL export can retain every relation.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" text not null unique,
  name text,
  email text,
  "loginMethod" text,
  role text not null default 'user' check (role in ('user', 'admin')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.allowed_team_emails (
  email text primary key,
  display_name text not null,
  created_at timestamptz not null default now()
);

insert into public.allowed_team_emails (email, display_name) values
  ('liz@thehumblevillage.org', 'Liz'),
  ('lauren@thehumblevillage.org', 'Lauren'),
  ('anna@thehumblevillage.org', 'Anna'),
  ('brenley@thehumblevillage.org', 'Brenley'),
  ('kirstenbham@gmail.com', 'Kirsten'),
  ('amydkerr@gmail.com', 'Amy'),
  ('brenleyb@gmail.com', 'Brenley'),
  ('laurenfoulger@gmail.com', 'Lauren'),
  ('emilylfeatherstone@gmail.com', 'Emily'),
  ('annaconnelly@gmail.com', 'Anna'),
  ('emary626@gmail.com', 'Emily')
on conflict (email) do update set display_name = excluded.display_name;

create table if not exists public.trips (
  id text primary key,
  name text not null,
  "startDate" date not null,
  "endDate" date not null,
  "teamMembers" text not null default '[]',
  notes text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.donors (
  id text primary key,
  name text not null,
  "contactName" text not null default '',
  email text,
  phone text,
  address text,
  "startDate" date not null,
  type text not null default 'one-time',
  tier text not null default 'individual',
  "contractEndDate" date,
  "recurringAmount" integer,
  "recurringFrequency" text,
  "cadenceDays" integer not null default 90,
  "cadenceDescription" text not null default '',
  "lastContactDate" date,
  status text not null default 'grey',
  "naruCircle" boolean not null default false,
  "donorTrip" boolean not null default false,
  "taxReceiptSent" boolean not null default false,
  "newsletterSubscribed" boolean not null default false,
  "manuallyInactive" boolean not null default false,
  "referredBy" text,
  "nextAction" text,
  "dismissedTasks" text,
  notes text,
  tags text,
  "tripId" text references public.trips(id) on delete set null,
  "totalDonatedCents" integer not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.donor_activities (
  id text primary key,
  "donorId" text not null references public.donors(id) on delete cascade,
  date date not null,
  author text not null,
  note text not null,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.donor_donations (
  id text primary key,
  "donorId" text not null references public.donors(id) on delete cascade,
  date date not null,
  "amountCents" integer not null,
  note text,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.donor_tasks (
  id text primary key,
  "donorId" text not null references public.donors(id) on delete cascade,
  kind text not null default 'onboarding',
  label text not null,
  "dueDate" date not null,
  "completedDate" date,
  "completedBy" text,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.trip_attendees (
  id text primary key,
  "tripId" text not null references public.trips(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  skills text not null default '[]',
  "isTeen" boolean not null default false,
  "speaksSpanish" boolean not null default false,
  confirmed boolean not null default false,
  "purchasedTicket" boolean not null default false,
  "knowsAtTHV" text,
  notes text,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.initiatives (
  id text primary key,
  title text not null,
  description text,
  "startDate" date not null,
  "endDate" date not null,
  owner text not null,
  status text not null default 'not-started',
  category text not null default '',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index if not exists donors_trip_id_idx on public.donors ("tripId");
create index if not exists donor_activities_donor_id_idx on public.donor_activities ("donorId", date desc);
create index if not exists donor_donations_donor_id_idx on public.donor_donations ("donorId", date desc);
create index if not exists donor_tasks_donor_id_idx on public.donor_tasks ("donorId", "dueDate");
create index if not exists trip_attendees_trip_id_idx on public.trip_attendees ("tripId");

-- Browser clients do not access the relationship data directly. The API function
-- uses a protected server connection, so RLS blocks accidental anonymous exposure.
alter table public.users enable row level security;
alter table public.allowed_team_emails enable row level security;
alter table public.donors enable row level security;
alter table public.donor_activities enable row level security;
alter table public.donor_donations enable row level security;
alter table public.donor_tasks enable row level security;
alter table public.trips enable row level security;
alter table public.trip_attendees enable row level security;
alter table public.initiatives enable row level security;
